import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans'
});

export const metadata: Metadata = {
    title: 'DonanBs',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body
                className={cn(
                    'dark min-h-screen bg-background text-foreground font-sans antialiased',
                    fontSans.variable
                )}
            >
                <main className='max-w-2xl min-h-screen m-auto'>
                    <section className='p-5 flex flex-col min-h-screen justify-center'>
                        {children}
                    </section>
                </main>
            </body>
        </html>
    );
}
